In [2]:
import numpy as np #Practice on Numpy

In [22]:
n1 = np.array([1,2,3,4,5]) #Array
n1

array([1, 2, 3, 4, 5])

In [24]:
n2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
n2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [3]:
n3 = np.zeros((2,3)) #Zeros
n3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
n4 = np.zeros((6,6)) #Zeros
n4

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
n5 = np.full((3,3),(5)) #Full
n5

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [8]:
n6 = np.full((3,8),(7)) #Full
n6

array([[7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7]])

In [16]:
n7 = np.arange(1,50) # ARange
n7

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [19]:
n8 = np.arange(0,50, 5) # ARange
n8

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [21]:
n9 = np.random.randint(1,100,5) #Arrays with Rand
n9

array([81, 58, 72, 99,  4])

In [26]:
n10 = np.array([[1,2,3,4,5],[6,7,8,9,10]]) #Shape
n10.shape

(2, 5)

In [28]:
n10.shape = (5,2) #Shape
n10.shape
n10

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])